### ISSUE TITLE
Deprecation Error

### ISSUE THREAD

**Issue by sinistersig** [navicstein/rod-stream#2]
Thanks, for the package I tried using it but ran into an issue where the `whitelisted-extension-id` flag is now deprecated.  The message instructs to use `allowlisted-extension-id` instead. I made the changes and tested them out and they work. I could submit a PR if you'd like.

**Comment by steinathan** [comment]
Sure, please do ... i have a branch that also fixes the the `whitelisted-extension-id` flag
https://github.com/navicstein/rod-stream/tree/hotfix/allowlisted-extension

**Comment by mikelorant** [comment]
@navicstein Can we get this fix merged back into the `main` branch? Be aware that the hot fix branch also has some unrelated changes.

I've got some further improvements to add and it would be useful to have the `main` branch up to date.

**Comment by steinathan** [comment]
I’ll do that

**Comment by mikelorant** [comment]
If you need some help splitting it up, happy to help out. I've got some ambitious plans with your extension and wanting to use it in a popular repository.
